models/Job.php
<?php
/**
 * Created by PhpStorm.
 * User: developer
 * Date: 25/01/2018
 * Time: 11:41
 */

namespace app\models;

use yii\db\ActiveRecord;

class Job extends ActiveRecord
{
    public function getLocation()
    {
        return $this->hasOne(Location::className(), ['id' => 'location_id']);
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\ApplyForm;
use app\models\User;
use app\models\Job;
use yii\web\UploadedFile;
use yii\data\Pagination;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays the home page to the website.
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Displays the login page allowing for users to login.
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {

            //Based on the user's role id, redirect them to their appropriate dashboard.
            if(\Yii::$app->session->get('user.role_id') == 1) {
                return $this->redirect(['user-dashboard/index']);
            } else if(\Yii::$app->session->get('user.role_id') == 2) {
                return $this->redirect(['employer-dashboard/index']);
            } else if(\Yii::$app->session->get('user.role_id') == 3) {
                return $this->redirect(['admin-dashboard/index']);
            } else {
                return $this->goBack();
            }

        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Used to allow the user to logout.
     */
    public function actionLogout()
    {
        //User is logging out, destroy the session.
        \Yii::$app->session->remove('user.role_id');
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Used to allow users of the website to view the jobs posted.
     * Allows for filtering by tags.
     */
    public function actionJobs() {
        $jobs = Job::find()->where(['status' => 1])->orderBy('expiry_date');

        $tags = \Yii::$app->request->get('tag');

        if(!is_null($tags)) {
            $jobs->andWhere(['like','tags', $tags]);
        }

        $countQuery = clone $jobs;

        $pages = new Pagination(['defaultPageSize' => 5, 'totalCount' => $countQuery->count()]);

        $models = $jobs->offset($pages->offset)
            ->limit($pages->limit)
            ->all();

        return $this->render('jobs', [
            'jobs' => $models,
            'pages' => $pages
        ]);
    }

    /**
     * Used to display the view page allowing for users to see the full detailed view of the job listing selected.
     * param: int $id - Id of the job listing.
     */
    public function actionView($id) {
        $show_form = false;
        $submitted = false;
        if(!Yii::$app->user->isGuest && \Yii::$app->session->get('user.role_id') == 1) {
            $show_form = true;
        }

        $job = Job::find()->where(['id' => $id])->one();
        $model = new ApplyForm();
        if (Yii::$app->request->isPost) {
            $model->cv = UploadedFile::getInstance($model, 'cv');
            if ($model->apply($id)) {
                // file is uploaded successfully
                $submitted = true;
            }
        }

        return $this->render('view', [
            'job' => $job,
            'model' => $model,
            'show_form' => $show_form,
            'submitted' => $submitted
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        We are JobBoard, the graduate careers platform designed to bring graduates and employers together.
    </p>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Url;

$this->title = 'JobBoard Home';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Welcome to JobBoard.</h1>

        <p class="lead">We are here to help you find the perfect job.</p>

        <p><a class="btn btn-lg btn-success" href="<?= Url::toRoute(['site/jobs']); ?>">Get started Here.</a></p>
    </div>
</div>

views/site/jobs.php
<?php
/**
 * Created by PhpStorm.
 * User: developer
 * Date: 26/01/2018
 * Time: 21:23
 */

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\LinkPager;

$this->title = 'Job List';
$this->params['breadcrumbs'][] = $this->title;

?>

<div class="container">
    <h1>Job List</h1>

    <div class="col-xs-12 filters">
        <form method="get" action="<?= htmlspecialchars(Yii::$app->request->url); ?>">
            <input type="text" name="tag" value="" />
            <button type="submit">Filter</button>
        </form>
    </div>

    <?php if($jobs): ?>
        <div class="job-container col-xs-12">
            <ul class="job-list">
                <?php foreach($jobs as $job): ?>

                    <li class="job-preview">
                        <div class="content float-left col-xs-12 col-sm-6">
                            <h4 class="job-title">
                                <?= Html::encode($job->title); ?>
                            </h4>
                            <h5 class="company">
                                <?= Html::encode($job->location->location) ?>
                            </h5>
                        </div>
                        <div class="col-xs-12 col-sm-6">
                            <div class="options-container float-right">
                                <div class="col-xs-12">
                                    <a href="<?= Url::toRoute(['site/view', 'id' => $job->id]); ?>" class="btn btn-apply no-margin float-right">
                                        View
                                    </a>
                                </div>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ul>

            <?=
               LinkPager::widget([
                    'pagination' => $pages,
                ]);
            ?>

        </div>
    <?php else: ?>
        <p>Sorry, there are currently no jobs. Please check back later.</p>
    <?php endif; ?>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->label('Email')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>
</div>

views/site/view.php
<?php
/**
 * Created by PhpStorm.
 * User: developer
 * Date: 28/01/2018
 * Time: 12:29
 */

use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;

$this->title = 'Job';
$this->params['breadcrumbs'][] = $this->title;

?>

<div id="individual-job" class="container">
    <div class="text-center main-info">
        <h1><?= Html::encode($job->title);  ?></h1>
        <label>Company: <span class="no-bold"><?= Html::encode($job->company_name);  ?></span></label>
        <label>Location: <span class="no-bold"><?= Html::encode($job->location->location);  ?></span></label>
        <label>Salary: <span class="no-bold"><?= Html::encode($job->salary);  ?></span></label>
        <label>Date: <span class="no-bold"><?= Html::encode(date("d/m/Y", strtotime($job->expiry_date)));  ?></span></label>
    </div>
    <div class="description">
        <h2>Description:</h2>
        <p>
            <?= Html::encode($job->description);  ?>
        </p>
    </div>
    <div class="tags">
        <h2>Tags:</h2>
        <p>
            <?= Html::encode($job->tags);  ?>
        </p>
    </div>
</div>

<div class="apply-form container">
    <?php if($show_form): ?>
        <?php if($submitted): ?>
            <p>Thank you for applying, your cv has been sent.</p>
        <?php else: ?>
            <h2>Apply</h2>

            <p>Please upload your CV to apply:</p>

            <?php $form = ActiveForm::begin([
                'id' => 'apply-form',
                'layout' => 'horizontal',
                'fieldConfig' => [
                    'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
                    'labelOptions' => ['class' => 'col-lg-1 control-label'],
                ],
            ]); ?>

            <?= $form->field($model, 'cv')->fileInput() ?>

            <div class="form-group">
                <div class="col-lg-offset-1 col-lg-11">
                    <?= Html::submitButton('Apply', ['class' => 'btn btn-primary', 'name' => 'apply-button']) ?>
                </div>
            </div>

            <?php ActiveForm::end(); ?>
        <?php endif; ?>
    <?php else: ?>
        <p>Please be logged in to apply.</p>
    <?php endif; ?>
</div>