models/Job.php
<?php
/**
 * Created by PhpStorm.
 * User: developer
 * Date: 25/01/2018
 * Time: 11:41
 */

namespace app\models;

use yii\db\ActiveRecord;

class Job extends ActiveRecord
{
    public function getLocation()
    {
        return $this->hasOne(Location::className(), ['id' => 'location_id']);
    }
}

controllers/AdminDashboardController.php
<?php
/**
 * Created by PhpStorm.
 * User: developer
 * Date: 26/01/2018
 * Time: 15:10
 */

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\Location;
use yii\helpers\ArrayHelper;
use app\models\User;
use app\models\Role;
use app\models\Job;
use yii\data\Pagination;

class AdminDashboardController extends Controller
{
    /**
     * Function used to do a check on start up.
     * This check is whether the user has the correct credentials.
     */
    public function init() {
        if(\Yii::$app->session->get('user.role_id') != 3) {
            return $this->goHome();
        }
    }

    /**
     * Used to display the index page of the admin controller.
     * This page shows basic stats of the website.
     * Number of normal and employer users + number of jobs listed on the site.
     */
    public function actionIndex() {
        $data['normal_users'] = User::find()->joinWith('role')->where(['user_roles.role_id' => 1])->count();
        $data['employer_users'] = User::find()->joinWith('role')->where(['user_roles.role_id' => 2])->count();
        $data['jobs'] = Job::find()->where(['status' => 1])->count();

        return $this->render('index', [
            'data' => $data
        ]);
    }

    /**
     * Used to display the users view.
     * This view shows a list of all the users on the site.
     * Also has a filter to filter between the types of users.
     */
    public function actionUsers() {
        $users = User::find()->where(['status' => 1]);

        $role = \Yii::$app->request->get('user-roles');

        if(!is_null($role)) {
            $users->joinWith('user_roles')->where(['user_roles.role_id' => $role]);
        }

        //TODO - Change for using sql.
        $countQuery = clone $users;

        if($users) {
            $roles = Role::find()->all();
        }

        $pages = new Pagination(['defaultPageSize' => 10, 'totalCount' => $countQuery->count()]);

        $model = $users->offset($pages->offset)
            ->limit($pages->limit)
            ->all();

        return $this->render('users', [
            'users' => $model,
            'roles' => $roles,
            'pages' => $pages
        ]);
    }

    /**
     * Used to show the jobs view.
     * This view shows all the current jobs posted on the site.
     * Also has a filter for filtering the jobs by tags.
     */
    public function actionJobs() {
        $jobs = Job::find()->where(['status' => 1])->orderBy('expiry_date');

        $tags = \Yii::$app->request->get('tag');

        if(!is_null($tags)) {
            $jobs->andWhere(['like','tags', $tags]);
        }

        $countQuery = clone $jobs;

        $pages = new Pagination(['defaultPageSize' => 5, 'totalCount' => $countQuery->count()]);

        $model = $jobs->offset($pages->offset)
            ->limit($pages->limit)
            ->all();

        return $this->render('jobs', [
            'jobs' => $model,
            'pages' => $pages
        ]);
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\ApplyForm;
use app\models\User;
use app\models\Job;
use yii\web\UploadedFile;
use yii\data\Pagination;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays the home page to the website.
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Displays the login page allowing for users to login.
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {

            //Based on the user's role id, redirect them to their appropriate dashboard.
            if(\Yii::$app->session->get('user.role_id') == 1) {
                return $this->redirect(['user-dashboard/index']);
            } else if(\Yii::$app->session->get('user.role_id') == 2) {
                return $this->redirect(['employer-dashboard/index']);
            } else if(\Yii::$app->session->get('user.role_id') == 3) {
                return $this->redirect(['admin-dashboard/index']);
            } else {
                return $this->goBack();
            }

        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Used to allow the user to logout.
     */
    public function actionLogout()
    {
        //User is logging out, destroy the session.
        \Yii::$app->session->remove('user.role_id');
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Used to allow users of the website to view the jobs posted.
     * Allows for filtering by tags.
     */
    public function actionJobs() {
        $jobs = Job::find()->where(['status' => 1])->orderBy('expiry_date');

        $tags = \Yii::$app->request->get('tag');

        if(!is_null($tags)) {
            $jobs->andWhere(['like','tags', $tags]);
        }

        $countQuery = clone $jobs;

        $pages = new Pagination(['defaultPageSize' => 5, 'totalCount' => $countQuery->count()]);

        $models = $jobs->offset($pages->offset)
            ->limit($pages->limit)
            ->all();

        return $this->render('jobs', [
            'jobs' => $models,
            'pages' => $pages
        ]);
    }

    /**
     * Used to display the view page allowing for users to see the full detailed view of the job listing selected.
     * param: int $id - Id of the job listing.
     */
    public function actionView($id) {
        $show_form = false;
        $submitted = false;
        if(!Yii::$app->user->isGuest && \Yii::$app->session->get('user.role_id') == 1) {
            $show_form = true;
        }

        $job = Job::find()->where(['id' => $id])->one();
        $model = new ApplyForm();
        if (Yii::$app->request->isPost) {
            $model->cv = UploadedFile::getInstance($model, 'cv');
            if ($model->apply($id)) {
                // file is uploaded successfully
                $submitted = true;
            }
        }

        return $this->render('view', [
            'job' => $job,
            'model' => $model,
            'show_form' => $show_form,
            'submitted' => $submitted
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
}

views/admin-dashboard/index.php
<?php
/**
 * Created by PhpStorm.
 * User: developer
 * Date: 26/01/2018
 * Time: 15:10
 */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;

$this->title = 'Admin Dashboard';
$this->params['breadcrumbs'][] = $this->title;

?>


<div id="admin-home" class="container center-block">
    <h1>Your Dashboard</h1>


    <div class="col-xs-12 col-md-4 text-center stat-container">
        <label>Normal Users</label>
        <span><?= $data['normal_users'] ?></span>
        <a href="<?= Url::toRoute(['admin-dashboard/users']); ?>/?user-roles=1">
            <button class="btn btn-primary">View</button>
        </a>
    </div>
    <div class="col-xs-12 col-md-4 text-center stat-container">
        <label>Employer Users</label>
        <span><?= $data['employer_users'] ?></span>
        <a href="<?= Url::toRoute(['admin-dashboard/users']); ?>/?user-roles=2">
            <button class="btn btn-primary">View</button>
        </a>
    </div>
    <div class="col-xs-12 col-md-4 text-center stat-container">
        <label>Jobs Posted</label>
        <span><?= $data['jobs'] ?></span>
        <a href="<?= Url::toRoute(['admin-dashboard/jobs']); ?>">
            <button class="btn btn-primary">View</button>
        </a>
    </div>
</div>

views/admin-dashboard/jobs.php
<?php
/**
 * Created by PhpStorm.
 * User: developer
 * Date: 26/01/2018
 * Time: 21:23
 */

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\LinkPager;

$this->title = 'Admin Dashboard - Job List';
$this->params['breadcrumbs'][] = $this->title;

?>

<div class="container">
    <h1>Job List</h1>

    <div class="filters">
        <form method="get" action="<?= htmlspecialchars(Yii::$app->request->url); ?>">
            <input type="text" name="tag" value="" />
            <button type="submit">Filter</button>
        </form>
    </div>

    <?php if($jobs): ?>
        <div class="job-container col-xs-12">
            <ul class="job-list">
                <?php foreach($jobs as $job): ?>

                    <li class="job-preview">
                        <div class="content float-left col-xs-12 col-sm-6">
                            <h4 class="job-title">
                                <?= Html::encode($job->title); ?>
                            </h4>
                            <h5 class="company">
                                <?= Html::encode($job->location->location) ?>
                            </h5>
                        </div>
                        <div class="col-xs-12 col-sm-6">
                            <div class="options-container float-right">
                                <div class="col-xs-12">
                                    <a href="<?= Url::toRoute(['site/view', 'id' => $job->id]); ?>" class="btn btn-apply no-margin float-right">
                                        View
                                    </a>
                                </div>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ul>

            <?=
               LinkPager::widget([
                    'pagination' => $pages,
                ]);
            ?>

        </div>
    <?php else: ?>
        <p>Sorry, there are currently no jobs. Please check back later.</p>
    <?php endif; ?>
</div>

views/admin-dashboard/users.php
<?php
/**
 * Created by PhpStorm.
 * User: developer
 * Date: 26/01/2018
 * Time: 15:48
 */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\widgets\LinkPager;

$this->title = 'Admin Dashboard - User List';
$this->params['breadcrumbs'][] = $this->title;

?>


<div id="admin-list" class="container center-block">
    <h1>User List</h1>

    <?php if($users): ?>
        <div class="filters">
            <form method="get" action="<?= htmlspecialchars(Yii::$app->request->url); ?>">
                <select name="user-roles">
                    <?php foreach($roles as $role): ?>
                        <option name="<?= Html::encode($role->role); ?>" value="<?= $role->id; ?>">
                            <?= Html::encode($role->role); ?>
                        </option>
                    <?php endforeach; ?>
                </select>
                <button type="submit">Filter</button>
            </form>
        </div>

        <table class="table table-striped">
            <thead>
                <tr>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Email</th>
                    <th>Phone</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($users as $user): ?>
                    <tr>
                        <td><?= Html::encode($user->first_name) ?></td>
                        <td><?= Html::encode($user->last_name) ?></td>
                        <td><?= Html::encode($user->username) ?></td>
                        <td><?= Html::encode($user->phone) ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>

        <?=
            LinkPager::widget([
                'pagination' => $pages,
            ]);
        ?>

    <?php else: ?>
        <p>Currently there are no users.</p>
    <?php endif; ?>

</div>